language: ruby

rvm:
  - jruby
  - rbx-2
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2

bundler_args: --without development

sudo: false

matrix:
  allow_failures:
    - rvm: jruby
    - rvm: rbx-2
    - rvm: 1.9.3

notifications:
  emails: true
